### PR TITLE
[Frontend] Add global selection color & "text" attribute to buttons

### PR DESCRIPTION
**Pull request by lerichardson**
[Frontend]
1. Add ::selection psuedoclass to globals, so when you select a piece of text, it looks like this instead of the default
image
2. Add "text" attribute to buttons, so now you can add text like this:
    ```js
      <Button colour={"blue"} text={"testing testing 1 2 3"} />
    ```
Which will return something like this:
image

### CODE REVIEW

**Comment by lerichardson** [comment]
^
 |
Yeah I committed to the wrong branch. I reverted it, and you can ignore that.

**Review by edazpotato — CHANGES_REQUESTED** [review]
Interesting suggestions, but please make sure to update the stories for the changed component. 

Also, I know it's not technically necessary, but to keep it consistent with all the other hex colours, could you please change the `#fff` to a `#ffffff`.

**Comment by edazpotato** [comment]
I like the selection colour (although we'll need to wait for @TheModdedChicken's approval on that), but why add a required property to buttons when text can already be passed in the children prop?

**Comment by TheModdedChicken** [comment]
The selection color seems good to me 👍

**Comment by lerichardson** [comment]
> Interesting suggestions, but please make sure to update the stories for the changed component. 
> 
> Also, I know it's not technically necessary, but to keep it consistent with all the other hex colours, could you please change the `#fff` to a `#ffffff`.

Ok, cooking up a commit right now.
> why add a required property to buttons when text can already be passed in the children prop

Just seems a bit easier and more clear to me.

**Comment by lerichardson** [comment]
Side note, what needs work most? I'd like to help out as much as possible but it feels like I'm blindly trying to figure out what needs work

**Comment by edazpotato** [comment]
There's a list of the components/pages that need to be built in React on the [initial release](https://github.com/edazpotato/Micro/projects/1) project. If you want to work on the backend, there isn't as much of a clear to-do list set out, but you can look at the Figma designs to get an idea of what the requirements would be.

**Comment by lerichardson** [comment]
Alrighty, added stories and changed it to `#ffffff`

**Comment by edazpotato** [comment]
How about we make `Button`s require either children or text but not both? That way you don't need to pass empty strings to them when you want (for example) a grey button with an SVG icon inside it. I'll happily make the change

**Comment by lerichardson** [comment]
Alright, makes sense, but what if I just made the "text" optional? Would that solve the problem?

**Comment by lerichardson** [comment]
Alright, how's that?

**Comment by edazpotato** [comment]
Looks good to me!

**Review by edazpotato — APPROVED** [review]

**Comment by edazpotato** [comment]
Hey @lerichardson, would you be interested in joining our core team of contributors? You seem very keen

**Comment by lerichardson** [comment]
Sure!

**Comment by edazpotato** [comment]
If you have Discord, I'll add you to a channel we use for discussing things.

**Comment by lerichardson** [comment]
DM it to me, Litbelb#4112

**Pull request merged**
