### PR TITLE
Add MeterBar component

### PR DESCRIPTION
**Pull request by edazpotato**
This is a pull request to add the MeterBar component. I'm making this a pull request instead of committing it directly because there are a lot of things that I'm doing in this component that could be debated. 

For example, people could have reasons for:
- Using some sort of SVG element instead of `<span>` elements for the actual bar,
- Using a normal markup element instead of an SVG `<rect />`s for the colour legend.
Some other things that could also be discussed include:
- API design - Currently everything is done through props, but we could go for a more react-ey approach using composable sub-components.
- Internal methods - Some of the utility functions in the component file could be extracted to their own utility file, either component-specific or for the whole app.

## Preview
Here's a preview of what it currently looks like (inside a card).
Light mode:
image
Dark mode:
image

## Checklist
  - [x] I have updated Type definitions
  - [x] All the linter checks pass

  - [x] I have updated / added new stories for affected components 

## Waiver
I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.

### CODE REVIEW

**Review by CyberFlameGO — APPROVED** [review]
Looks good to me, seems like a useful change and I don't see any conflicts

**Review by lerichardson — APPROVED** [review]
A couple fixes needed later on, but for now LGTM!

**Review by lerichardson — APPROVED** [review]
LGTM

**Review by TheModdedChicken — APPROVED** [review]
Great work, this looks fantastic!

**Pull request merged**
