### PR TITLE
Fix backend updater

### PR DESCRIPTION
**Pull request by TheModdedChicken**

### CODE REVIEW

**Comment by edazpotato** [comment]
I see no issues with this pr - it it ready to merge?

**Comment by TheModdedChicken** [comment]
Ah no not yet. Still working on it because Linux still isn't playing nice with my code.
Originally I thought I could replace the code while the server is running because deleting the code doesn't seem to affect it, but when I tried running the following commands it didn't seem to do anything:
`git reset --hard HEAD && git clean -df && git pull && yarn install && yarn run prod`

Though one thing that might be the cause of this not working is the timing for when the server restarts itself.

**Comment by TheModdedChicken** [comment]
Never mind, I figured out a solution.

**Comment by TheModdedChicken** [comment]
@edazpotato You should be in the clear to upload this to your VPS without any issues now.

**Pull request merged**
