### PR TITLE
minor changes to docs&gitignore

### PR DESCRIPTION
**Pull request by CyberFlameGO**
minor changes

### CODE REVIEW

**Comment by lerichardson** [comment]
I like the README updates, but I (and I think @edazpotato - TBD) still want `storybook-static` to be ignored. It's a lot like adding `node_modules`. It adds a lot of files that can (and should) be added from the client anyways.

**Comment by lerichardson** [comment]
I can edit it myself if you'd like

**Review by edazpotato — APPROVED** [review]
Looks good. @lerichardson it looks like the PR author just moved `storybook-static/` to the bottom of the file.

**Comment by lerichardson** [comment]
> Looks good. @lerichardson it looks like the PR author just moved `storybook-static/` to the bottom of the file.

I'm pretty stupid, as you can tell.

Sorry @CyberFlameGO

**Comment by CyberFlameGO** [comment]
All good haha, diff is confusing. If you find issues with my contributions, you're more than welcome to just edit them; I've given maintainers access to edits

**Pull request merged**
